spring.application.name=atendimento

# ===================================================================
# CONFIGURAÇÃO DO POSTGRESQL
# ===================================================================
# Altere 'localhost:5432' se a sua porta for diferente, e 'atendimento_db' é o nome da base de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/atendimento_db
spring.datasource.username=postgres
spring.datasource.password=Suporte@01
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURAÇÃO DO JPA / HIERMATE
# ===================================================================
# 'update' faz com que o Hibernate crie ou atualize as tabelas automaticamente sem apagar os dados existentes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Exibe as consultas SQL no terminal para facilitar o desenvolvimento
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false